export const glossaryTerms = [
  // Trading Strategies
  {
    id: 1,
    term: "Arbitrage",
    acronym: "ARB",
    category: "strategies",
    description:
      "The simultaneous purchase and sale of the same asset in different markets to profit from price differences.",
    formula: "Profit = Price_Market_A - Price_Market_B - Transaction_Costs",
    example:
      "If Bitcoin trades at $50,000 on Exchange A and $50,100 on Exchange B, buy on A and sell on B for $100 profit minus fees.",
    related: ["Statistical Arbitrage", "Triangular Arbitrage", "Pairs Trading"],
  },
  {
    id: 2,
    term: "Mean Reversion",
    category: "strategies",
    description:
      "A trading strategy based on the assumption that asset prices will revert to their historical average over time.",
    formula: "Entry Signal = (Current_Price - Moving_Average) / Standard_Deviation > Threshold",
    example:
      "If a stock typically trades at $100 but drops to $90, a mean reversion strategy would buy expecting a return to $100.",
    related: ["Bollinger Bands", "RSI", "Z-Score"],
  },
  {
    id: 3,
    term: "Momentum Trading",
    category: "strategies",
    description:
      "A strategy that aims to capitalize on the continuance of existing market trends by buying assets showing upward price movement.",
    formula: "Momentum = Price_Today - Price_N_Days_Ago",
    example: "Buy stocks that have risen 20% in the past month, expecting continued upward movement.",
    related: ["Trend Following", "MACD", "Rate of Change"],
  },
  {
    id: 4,
    term: "Statistical Arbitrage",
    acronym: "Stat Arb",
    category: "strategies",
    description:
      "A quantitative trading strategy that uses statistical models to identify pricing inefficiencies between related securities.",
    formula: "Signal = (Spread - Mean) / StdDev > Entry_Threshold",
    example:
      "Trade pairs of stocks that historically move together when their price relationship deviates from normal.",
    related: ["Pairs Trading", "Cointegration", "Market Neutral"],
  },
  {
    id: 5,
    term: "Market Making",
    category: "strategies",
    description:
      "Providing liquidity by simultaneously posting buy and sell orders, profiting from the bid-ask spread.",
    formula: "Profit = Volume × (Ask_Price - Bid_Price) - Inventory_Risk",
    example: "Quote BTC at $50,000 bid and $50,010 ask, earning $10 spread on each round trip.",
    related: ["Liquidity Provider", "Spread", "Order Book"],
  },
  {
    id: 6,
    term: "Delta Neutral",
    category: "strategies",
    description:
      "A portfolio strategy that maintains zero net exposure to market movements by balancing positive and negative deltas.",
    formula: "Portfolio_Delta = Σ(Position_Size × Option_Delta) = 0",
    example: "Long 100 shares (delta = 100) and long 2 put options with -50 delta each.",
    related: ["Greeks", "Hedging", "Options Strategies"],
  },
  {
    id: 7,
    term: "Carry Trade",
    category: "strategies",
    description: "Borrowing in a low-interest currency to invest in a higher-yielding currency or asset.",
    formula: "Profit = Interest_Differential - Exchange_Rate_Movement",
    example: "Borrow Japanese Yen at 0.1% to invest in Australian bonds yielding 4%.",
    related: ["Interest Rate Differential", "Currency Risk", "Funding Currency"],
  },
  {
    id: 8,
    term: "Calendar Spread",
    category: "strategies",
    description:
      "An options strategy involving simultaneous purchase and sale of options with same strike but different expiration dates.",
    formula: "Profit = Long_Term_Option_Value - Short_Term_Option_Value - Initial_Cost",
    example: "Buy December call, sell November call on same stock at same strike price.",
    related: ["Time Decay", "Theta", "Options Spread"],
  },
  {
    id: 9,
    term: "Triangular Arbitrage",
    category: "strategies",
    description: "Exploiting price discrepancies between three related currency pairs in the foreign exchange market.",
    formula: "Profit = Start_Amount × Rate_1 × Rate_2 × Rate_3 - Start_Amount",
    example: "Convert USD→EUR→GBP→USD when the cross rates offer a profit opportunity.",
    related: ["Cross Rates", "Forex Arbitrage", "Currency Pairs"],
  },
  {
    id: 10,
    term: "Volatility Arbitrage",
    category: "strategies",
    description: "Trading the difference between implied volatility and realized volatility of options.",
    formula: "Edge = Implied_Volatility - Realized_Volatility",
    example: "If options imply 30% volatility but you expect 20%, sell options to capture the premium.",
    related: ["Implied Volatility", "Realized Volatility", "Vega"],
  },

  // Technical Indicators
  {
    id: 11,
    term: "RSI",
    acronym: "Relative Strength Index",
    category: "indicators",
    description:
      "A momentum oscillator that measures the speed and magnitude of price changes to identify overbought or oversold conditions.",
    formula: "RSI = 100 - (100 / (1 + RS)), where RS = Avg_Gain / Avg_Loss",
    example: "RSI above 70 suggests overbought (potential sell), below 30 suggests oversold (potential buy).",
    related: ["Stochastic", "MACD", "Momentum"],
  },
  {
    id: 12,
    term: "MACD",
    acronym: "Moving Average Convergence Divergence",
    category: "indicators",
    description: "A trend-following momentum indicator showing the relationship between two moving averages of prices.",
    formula: "MACD = EMA(12) - EMA(26), Signal = EMA(9) of MACD",
    example: "Buy when MACD crosses above signal line, sell when it crosses below.",
    related: ["EMA", "Signal Line", "Histogram"],
  },
  {
    id: 13,
    term: "Bollinger Bands",
    category: "indicators",
    description:
      "A volatility indicator consisting of a moving average and two standard deviation lines above and below it.",
    formula: "Upper Band = MA + (K × σ), Lower Band = MA - (K × σ)",
    example: "Price touching lower band may indicate oversold condition and potential bounce.",
    related: ["Standard Deviation", "Volatility", "Mean Reversion"],
  },
  {
    id: 14,
    term: "VWAP",
    acronym: "Volume Weighted Average Price",
    category: "indicators",
    description: "The average price weighted by volume, often used as a trading benchmark by institutional investors.",
    formula: "VWAP = Σ(Price × Volume) / Σ(Volume)",
    example: "Buy below VWAP for better-than-average entry, sell above for better exit.",
    related: ["TWAP", "Institutional Trading", "Benchmark"],
  },
  {
    id: 15,
    term: "ATR",
    acronym: "Average True Range",
    category: "indicators",
    description: "A volatility indicator that measures the average range of price movement over a specified period.",
    formula: "ATR = MA(max(H-L, |H-PC|, |L-PC|))",
    example: "Use 2× ATR for stop-loss placement to account for normal price volatility.",
    related: ["Volatility", "Stop Loss", "Position Sizing"],
  },
  {
    id: 16,
    term: "Stochastic Oscillator",
    category: "indicators",
    description: "A momentum indicator comparing closing price to price range over a specific period.",
    formula: "%K = 100 × (Close - Low_N) / (High_N - Low_N)",
    example: "Values above 80 indicate overbought, below 20 indicate oversold conditions.",
    related: ["RSI", "Momentum", "Oscillator"],
  },
  {
    id: 17,
    term: "Ichimoku Cloud",
    category: "indicators",
    description: "A comprehensive indicator showing support/resistance, trend direction, and momentum.",
    formula: "Cloud = Area between Senkou Span A and B",
    example: "Price above cloud indicates uptrend, below cloud indicates downtrend.",
    related: ["Trend Following", "Support/Resistance", "Japanese Candlesticks"],
  },
  {
    id: 18,
    term: "OBV",
    acronym: "On Balance Volume",
    category: "indicators",
    description: "A volume-based indicator that uses volume flow to predict price changes.",
    formula: "OBV = Previous_OBV ± Volume (based on price direction)",
    example: "Rising OBV with flat price suggests accumulation and potential breakout.",
    related: ["Volume Analysis", "Accumulation/Distribution", "Money Flow"],
  },
  {
    id: 19,
    term: "Fibonacci Retracement",
    category: "indicators",
    description: "A tool using horizontal lines to indicate support/resistance at key Fibonacci levels.",
    formula: "Levels = High - (High - Low) × Fibonacci_Ratio",
    example: "Common retracement levels are 23.6%, 38.2%, 50%, 61.8%, and 78.6%.",
    related: ["Support/Resistance", "Technical Analysis", "Golden Ratio"],
  },
  {
    id: 20,
    term: "ADX",
    acronym: "Average Directional Index",
    category: "indicators",
    description: "Measures trend strength regardless of direction, ranging from 0 to 100.",
    formula: "ADX = MA(DX), where DX = |+DI - -DI| / |+DI + -DI| × 100",
    example: "ADX > 25 indicates strong trend, < 20 indicates weak or no trend.",
    related: ["Trend Strength", "DMI", "Directional Movement"],
  },

  // Risk Management
  {
    id: 21,
    term: "Kelly Criterion",
    category: "risk",
    description: "A formula for determining optimal position size based on edge and win/loss ratio.",
    formula: "f* = (p × b - q) / b, where f* = fraction, p = win prob, q = loss prob, b = odds",
    example: "With 60% win rate and 2:1 reward/risk, Kelly suggests 20% position size.",
    related: ["Position Sizing", "Optimal f", "Risk of Ruin"],
  },
  {
    id: 22,
    term: "Sharpe Ratio",
    category: "risk",
    description: "A measure of risk-adjusted returns, comparing excess returns to volatility.",
    formula: "Sharpe = (Return - Risk_Free_Rate) / Standard_Deviation",
    example: "Sharpe ratio of 1.5 means 1.5% excess return per 1% of volatility risk.",
    related: ["Risk-Adjusted Returns", "Sortino Ratio", "Information Ratio"],
  },
  {
    id: 23,
    term: "Value at Risk",
    acronym: "VaR",
    category: "risk",
    description:
      "Statistical measure of potential portfolio loss over a specific time period at a given confidence level.",
    formula: "VaR = Portfolio_Value × σ × √t × Z-score",
    example: "95% VaR of $10,000 means 95% confidence losses won't exceed $10,000.",
    related: ["CVaR", "Expected Shortfall", "Risk Metrics"],
  },
  {
    id: 24,
    term: "Maximum Drawdown",
    category: "risk",
    description: "The largest peak-to-trough decline in portfolio value before a new peak is achieved.",
    formula: "Max_DD = (Trough_Value - Peak_Value) / Peak_Value × 100%",
    example: "A 20% max drawdown means the portfolio fell 20% from its highest point.",
    related: ["Recovery Period", "Underwater Curve", "Pain Index"],
  },
  {
    id: 25,
    term: "Risk Parity",
    category: "risk",
    description: "Portfolio allocation strategy that allocates risk equally across all assets rather than capital.",
    formula: "Weight_i = (1/σ_i) / Σ(1/σ_j)",
    example: "Allocate less capital to volatile assets and more to stable ones for equal risk.",
    related: ["Portfolio Theory", "Risk Budgeting", "Diversification"],
  },
  {
    id: 26,
    term: "Sortino Ratio",
    category: "risk",
    description: "Similar to Sharpe ratio but only considers downside volatility, not upside.",
    formula: "Sortino = (Return - Target) / Downside_Deviation",
    example: "Sortino of 2.0 indicates good returns relative to downside risk.",
    related: ["Sharpe Ratio", "Downside Risk", "Semi-Variance"],
  },
  {
    id: 27,
    term: "Beta",
    category: "risk",
    description: "Measure of an asset's volatility relative to the overall market.",
    formula: "β = Covariance(Asset, Market) / Variance(Market)",
    example: "Beta of 1.5 means asset moves 1.5% for every 1% market move.",
    related: ["Alpha", "CAPM", "Systematic Risk"],
  },
  {
    id: 28,
    term: "Calmar Ratio",
    category: "risk",
    description: "Risk-adjusted return metric comparing average annual return to maximum drawdown.",
    formula: "Calmar = Annual_Return / Max_Drawdown",
    example: "Calmar of 2.0 means earning 2% annually for each 1% of max drawdown risk.",
    related: ["Risk-Adjusted Returns", "Sterling Ratio", "Maximum Drawdown"],
  },
  {
    id: 29,
    term: "Greeks",
    category: "risk",
    description: "Risk measures for options positions: Delta, Gamma, Theta, Vega, and Rho.",
    example: "Delta of 0.5 means option price moves $0.50 for every $1 stock move.",
    related: ["Options Pricing", "Black-Scholes", "Risk Management"],
  },
  {
    id: 30,
    term: "Conditional VaR",
    acronym: "CVaR",
    category: "risk",
    description: "Expected loss given that loss exceeds the VaR threshold, also called Expected Shortfall.",
    formula: "CVaR = E[Loss | Loss > VaR]",
    example: "If 95% VaR is $10,000, CVaR might be $15,000 average loss in worst 5% scenarios.",
    related: ["Value at Risk", "Tail Risk", "Risk Metrics"],
  },

  // Quantitative Methods
  {
    id: 31,
    term: "Backtesting",
    category: "quant",
    description: "Testing a trading strategy on historical data to evaluate its performance.",
    formula: "Performance = Σ(Trade_PnL) - Costs - Slippage",
    example: "Test your strategy on 5 years of data before risking real capital.",
    related: ["Walk-Forward Analysis", "Out-of-Sample Testing", "Overfitting"],
  },
  {
    id: 32,
    term: "Monte Carlo Simulation",
    category: "quant",
    description: "Using random sampling to model probability distributions of possible outcomes.",
    formula: "Result = Average(N_Random_Simulations)",
    example: "Run 10,000 simulations to estimate probability of 20% drawdown.",
    related: ["Risk Analysis", "Stochastic Modeling", "Bootstrap"],
  },
  {
    id: 33,
    term: "Machine Learning",
    acronym: "ML",
    category: "quant",
    description: "Using algorithms to identify patterns and make predictions without explicit programming.",
    example: "Train neural network on price patterns to predict next-day movements.",
    related: ["Deep Learning", "Feature Engineering", "Random Forest"],
  },
  {
    id: 34,
    term: "Cointegration",
    category: "quant",
    description: "Statistical property where two time series move together maintaining stable relationship.",
    formula: "Y_t = α + β × X_t + ε_t (where ε_t is stationary)",
    example: "Gold and gold miners often cointegrate, suitable for pairs trading.",
    related: ["Stationarity", "ADF Test", "Pairs Trading"],
  },
  {
    id: 35,
    term: "Walk-Forward Analysis",
    category: "quant",
    description: "Optimization technique that tests strategy on rolling windows to avoid overfitting.",
    example: "Optimize on 2 years, test on 6 months, roll forward, repeat.",
    related: ["Backtesting", "Out-of-Sample", "Robustness Testing"],
  },
  {
    id: 36,
    term: "Principal Component Analysis",
    acronym: "PCA",
    category: "quant",
    description: "Dimensionality reduction technique to identify main drivers of returns.",
    formula: "PC = Eigenvectors × Standardized_Data",
    example: "Reduce 50 stock returns to 5 principal factors explaining 90% of variance.",
    related: ["Factor Models", "Eigenvalues", "Dimensionality Reduction"],
  },
  {
    id: 37,
    term: "Hidden Markov Model",
    acronym: "HMM",
    category: "quant",
    description: "Statistical model for systems with unobservable states, used for regime detection.",
    example: "Identify whether market is in trending or mean-reverting regime.",
    related: ["Regime Switching", "State Space Models", "Baum-Welch"],
  },
  {
    id: 38,
    term: "GARCH",
    acronym: "Generalized Autoregressive Conditional Heteroskedasticity",
    category: "quant",
    description: "Model for forecasting volatility that accounts for volatility clustering.",
    formula: "σ²_t = ω + α × ε²_t-1 + β × σ²_t-1",
    example: "Forecast tomorrow's volatility based on today's returns and volatility.",
    related: ["Volatility Modeling", "ARCH", "Heteroskedasticity"],
  },
  {
    id: 39,
    term: "Kalman Filter",
    category: "quant",
    description: "Algorithm for estimating unknown variables from noisy observations over time.",
    example: "Estimate true price from noisy market data or track hedge ratios dynamically.",
    related: ["State Estimation", "Signal Processing", "Pairs Trading"],
  },
  {
    id: 40,
    term: "Bootstrap",
    category: "quant",
    description: "Resampling method to estimate sampling distribution of a statistic.",
    example: "Resample returns 10,000 times to get confidence intervals for Sharpe ratio.",
    related: ["Monte Carlo", "Confidence Intervals", "Resampling"],
  },

  // Execution & Market Microstructure
  {
    id: 41,
    term: "Slippage",
    category: "execution",
    description: "Difference between expected and actual execution price due to market movement.",
    formula: "Slippage = Actual_Price - Expected_Price",
    example: "Placing market buy at $100 but filling at $100.50 due to fast market movement.",
    related: ["Market Impact", "Transaction Costs", "Liquidity"],
  },
  {
    id: 42,
    term: "Market Impact",
    category: "execution",
    description: "The effect of a trade on the market price, especially for large orders.",
    formula: "Impact = √(Order_Size / ADV) × Volatility × Impact_Coefficient",
    example: "Buying $10M of a stock with $100M daily volume might move price 0.5%.",
    related: ["Slippage", "Liquidity", "VWAP"],
  },
  {
    id: 43,
    term: "Order Types",
    category: "execution",
    description: "Different instructions for how orders should be executed: Market, Limit, Stop, etc.",
    example: "Limit order at $100 only executes at $100 or better, market order executes immediately.",
    related: ["Limit Order", "Market Order", "Stop Loss"],
  },
  {
    id: 44,
    term: "Dark Pool",
    category: "execution",
    description: "Private exchanges where large orders can be placed without revealing intentions.",
    example: "Execute 1M share block in dark pool to avoid moving the market.",
    related: ["Alternative Trading System", "Block Trading", "Liquidity"],
  },
  {
    id: 45,
    term: "TWAP",
    acronym: "Time Weighted Average Price",
    category: "execution",
    description: "Execution algorithm that spreads orders evenly over a specified time period.",
    formula: "TWAP = Σ(Price_i) / N_time_periods",
    example: "Buy 10,000 shares evenly over next 2 hours to minimize market impact.",
    related: ["VWAP", "Execution Algorithms", "Algorithmic Trading"],
  },
  {
    id: 46,
    term: "Iceberg Order",
    category: "execution",
    description: "Large order divided into smaller visible portions to hide true size.",
    example: "Show only 100 shares at a time of a 10,000 share order.",
    related: ["Hidden Orders", "Order Book", "Large Orders"],
  },
  {
    id: 47,
    term: "Fill or Kill",
    acronym: "FOK",
    category: "execution",
    description: "Order that must be executed immediately in full or cancelled entirely.",
    example: "FOK order for 1,000 shares at $50 - get all 1,000 or none.",
    related: ["Immediate or Cancel", "All or None", "Order Types"],
  },
  {
    id: 48,
    term: "Maker-Taker Model",
    category: "execution",
    description: "Fee structure where liquidity providers (makers) receive rebates while takers pay fees.",
    example: "Receive $0.002/share rebate for limit orders, pay $0.003/share for market orders.",
    related: ["Liquidity", "Exchange Fees", "Market Making"],
  },
  {
    id: 49,
    term: "Best Execution",
    category: "execution",
    description: "Legal obligation to execute orders at most favorable terms for the client.",
    example: "Route order to exchange with best price after considering all costs.",
    related: ["Order Routing", "NBBO", "Regulation NMS"],
  },
  {
    id: 50,
    term: "Latency",
    category: "execution",
    description: "Time delay between order submission and execution, critical for high-frequency trading.",
    formula: "Total_Latency = Network_Latency + Processing_Time + Exchange_Latency",
    example: "Reduce latency from 10ms to 1ms by colocating servers at exchange.",
    related: ["High-Frequency Trading", "Colocation", "Network Optimization"],
  },

  // Infrastructure & Technology
  {
    id: 51,
    term: "API",
    acronym: "Application Programming Interface",
    category: "infrastructure",
    description: "Set of protocols for building software applications to interact with trading platforms.",
    example: "Use Binance API to automatically execute trades from Python bot.",
    related: ["REST API", "WebSocket", "FIX Protocol"],
  },
  {
    id: 52,
    term: "WebSocket",
    category: "infrastructure",
    description: "Protocol providing full-duplex communication for real-time data streaming.",
    example: "Subscribe to WebSocket feed for live price updates instead of polling.",
    related: ["Real-time Data", "Streaming", "REST API"],
  },
  {
    id: 53,
    term: "FIX Protocol",
    acronym: "Financial Information eXchange",
    category: "infrastructure",
    description: "Electronic communications protocol for real-time securities transactions.",
    example: "Institutional traders use FIX for direct market access and order routing.",
    related: ["Order Routing", "Low Latency", "Institutional Trading"],
  },
  {
    id: 54,
    term: "Colocation",
    category: "infrastructure",
    description: "Placing trading servers physically close to exchange servers to minimize latency.",
    example: "Rent rack space in same data center as NYSE for microsecond advantage.",
    related: ["High-Frequency Trading", "Latency", "Infrastructure"],
  },
  {
    id: 55,
    term: "Order Book",
    category: "infrastructure",
    description: "Real-time list of buy and sell orders organized by price level.",
    example: "Level 2 data shows 10,000 shares bid at $99.95 and 5,000 offered at $100.05.",
    related: ["Market Depth", "Level 2 Data", "Bid-Ask Spread"],
  },
  {
    id: 56,
    term: "Matching Engine",
    category: "infrastructure",
    description: "Core system that matches buy and sell orders according to exchange rules.",
    example: "NASDAQ matching engine processes millions of orders per second.",
    related: ["Order Matching", "Exchange Technology", "FIFO/Pro-Rata"],
  },
  {
    id: 57,
    term: "Data Feed",
    category: "infrastructure",
    description: "Real-time stream of market data including prices, volumes, and order book.",
    example: "Subscribe to Level 2 data feed for full market depth information.",
    related: ["Market Data", "Real-time Data", "Historical Data"],
  },
  {
    id: 58,
    term: "Docker",
    category: "infrastructure",
    description: "Containerization platform for packaging and deploying trading applications.",
    example: "Deploy trading bot in Docker container for consistent environment.",
    related: ["Containerization", "Kubernetes", "DevOps"],
  },
  {
    id: 59,
    term: "Message Queue",
    category: "infrastructure",
    description: "System for asynchronous communication between different components of trading system.",
    example: "Use RabbitMQ to queue orders for processing during high volume periods.",
    related: ["RabbitMQ", "Kafka", "Event-Driven Architecture"],
  },
  {
    id: 60,
    term: "Time Series Database",
    category: "infrastructure",
    description: "Database optimized for storing and querying time-stamped data like prices.",
    example: "Store tick data in InfluxDB for efficient historical analysis.",
    related: ["InfluxDB", "TimescaleDB", "Database Architecture"],
  },

  // Market Analysis & Data
  {
    id: 61,
    term: "Technical Analysis",
    category: "analysis",
    description: "Analyzing statistical trends from trading activity to predict future price movements.",
    example: "Use chart patterns, indicators, and volume to make trading decisions.",
    related: ["Chart Patterns", "Indicators", "Price Action"],
  },
  {
    id: 62,
    term: "Fundamental Analysis",
    category: "analysis",
    description: "Evaluating securities by analyzing financial statements and economic factors.",
    example: "Analyze company earnings, revenue growth, and P/E ratios for stock valuation.",
    related: ["Financial Statements", "Valuation", "Economic Indicators"],
  },
  {
    id: 63,
    term: "Sentiment Analysis",
    category: "analysis",
    description: "Gauging market sentiment from news, social media, and other text sources.",
    example: "Analyze Twitter mentions to gauge retail investor sentiment on stocks.",
    related: ["Natural Language Processing", "Alternative Data", "Market Psychology"],
  },
  {
    id: 64,
    term: "Order Flow Analysis",
    category: "analysis",
    description: "Studying the flow of buy and sell orders to predict short-term price movements.",
    example: "Large buy orders at support levels indicate institutional accumulation.",
    related: ["Market Microstructure", "Volume Profile", "Footprint Charts"],
  },
  {
    id: 65,
    term: "Correlation Analysis",
    category: "analysis",
    description: "Measuring how different assets move in relation to each other.",
    formula: "ρ = Cov(X,Y) / (σ_X × σ_Y)",
    example: "Gold and USD typically have -0.7 correlation (inverse relationship).",
    related: ["Portfolio Diversification", "Covariance", "Beta"],
  },
  {
    id: 66,
    term: "Volume Profile",
    category: "analysis",
    description: "Histogram showing trading volume at different price levels over time.",
    example: "High volume node at $100 acts as strong support/resistance level.",
    related: ["Market Profile", "Value Area", "Point of Control"],
  },
  {
    id: 67,
    term: "Market Profile",
    category: "analysis",
    description: "Technical analysis tool showing time spent at each price level.",
    example: "Price spent 70% of day between $99-101, indicating balance area.",
    related: ["Volume Profile", "Value Area", "TPO"],
  },
  {
    id: 68,
    term: "Seasonality",
    category: "analysis",
    description: "Predictable patterns in asset prices based on time of year or month.",
    example: "Stock market typically strong in December (Santa Claus rally).",
    related: ["Calendar Effects", "Cyclical Analysis", "Pattern Recognition"],
  },
  {
    id: 69,
    term: "Intermarket Analysis",
    category: "analysis",
    description: "Analyzing relationships between different asset classes and markets.",
    example: "Rising bond yields often lead to falling stock prices.",
    related: ["Cross-Asset Analysis", "Correlation", "Market Relationships"],
  },
  {
    id: 70,
    term: "Alternative Data",
    category: "analysis",
    description: "Non-traditional data sources like satellite imagery, web traffic, or credit card data.",
    example: "Count cars in retailer parking lots via satellite to predict earnings.",
    related: ["Big Data", "Data Mining", "Unique Alpha"],
  },

  // Additional Advanced Terms
  {
    id: 71,
    term: "Alpha",
    category: "quant",
    description: "Excess return of an investment relative to a benchmark index.",
    formula: "α = Portfolio_Return - (Risk_Free + β × (Market_Return - Risk_Free))",
    example: "Fund returning 15% when market returned 10% has 5% alpha.",
    related: ["Beta", "CAPM", "Risk-Adjusted Returns"],
  },
  {
    id: 72,
    term: "High-Frequency Trading",
    acronym: "HFT",
    category: "strategies",
    description:
      "Algorithmic trading using powerful computers to execute large numbers of orders in fractions of a second.",
    example: "Execute thousands of trades per second to capture tiny price discrepancies.",
    related: ["Low Latency", "Market Making", "Colocation"],
  },
  {
    id: 73,
    term: "Black-Scholes Model",
    category: "quant",
    description: "Mathematical model for pricing European options and derivatives.",
    formula: "C = S₀×N(d₁) - K×e^(-rt)×N(d₂)",
    example: "Calculate fair value of call option given stock price, strike, time, and volatility.",
    related: ["Options Pricing", "Greeks", "Implied Volatility"],
  },
  {
    id: 74,
    term: "Gamma Scalping",
    category: "strategies",
    description: "Options strategy that profits from realized volatility by dynamically hedging gamma exposure.",
    example: "Buy straddle and hedge delta daily to capture volatility while staying market neutral.",
    related: ["Options Trading", "Gamma", "Dynamic Hedging"],
  },
  {
    id: 75,
    term: "Risk of Ruin",
    category: "risk",
    description: "Probability of losing entire trading capital given win rate and risk per trade.",
    formula: "RoR = ((1-p)/p)^(Capital/Risk_per_Trade)",
    example: "With 40% win rate risking 2% per trade, risk of ruin is 13.5%.",
    related: ["Kelly Criterion", "Position Sizing", "Capital Preservation"],
  },
  {
    id: 76,
    term: "Expectancy",
    category: "quant",
    description: "Average amount you expect to win or lose per trade.",
    formula: "E = (Win_Rate × Avg_Win) - (Loss_Rate × Avg_Loss)",
    example: "60% wins averaging $100, 40% losses averaging $100 = $20 expectancy.",
    related: ["Win Rate", "Risk Reward", "System Performance"],
  },
  {
    id: 77,
    term: "Profit Factor",
    category: "quant",
    description: "Ratio of gross profits to gross losses, measuring system profitability.",
    formula: "PF = Total_Profits / Total_Losses",
    example: "Profit factor of 1.5 means earning $1.50 for every $1.00 lost.",
    related: ["Performance Metrics", "System Evaluation", "Risk Reward"],
  },
  {
    id: 78,
    term: "Information Ratio",
    category: "risk",
    description: "Risk-adjusted measure of active return relative to a benchmark.",
    formula: "IR = (Portfolio_Return - Benchmark_Return) / Tracking_Error",
    example: "IR of 0.5 means 0.5% excess return per 1% of tracking error.",
    related: ["Sharpe Ratio", "Active Management", "Tracking Error"],
  },
  {
    id: 79,
    term: "Quantile Regression",
    category: "quant",
    description: "Statistical technique to estimate conditional quantiles of response variable.",
    example: "Estimate 5th percentile of returns for downside risk analysis.",
    related: ["Regression Analysis", "Risk Modeling", "Tail Risk"],
  },
  {
    id: 80,
    term: "Overnight Risk",
    category: "risk",
    description: "Risk of adverse price movements when markets are closed.",
    example: "Stock closes at $100, opens at $95 due to overnight news.",
    related: ["Gap Risk", "After-Hours Trading", "Position Management"],
  },
  {
    id: 81,
    term: "Liquidity Risk",
    category: "risk",
    description: "Risk that a position cannot be closed quickly without significant price impact.",
    example: "Unable to sell large position in small-cap stock without 10% slippage.",
    related: ["Market Impact", "Bid-Ask Spread", "Volume"],
  },
  {
    id: 82,
    term: "Counterparty Risk",
    category: "risk",
    description: "Risk that the other party in a transaction may default on obligations.",
    example: "Exchange going bankrupt and losing deposited funds.",
    related: ["Credit Risk", "Settlement Risk", "Prime Broker"],
  },
  {
    id: 83,
    term: "Fat Tails",
    category: "quant",
    description: "Statistical property where extreme events occur more frequently than normal distribution predicts.",
    example: "Market crashes happen more often than bell curve suggests.",
    related: ["Kurtosis", "Black Swan", "Tail Risk"],
  },
  {
    id: 84,
    term: "Autocorrelation",
    category: "quant",
    description: "Correlation of a time series with a delayed copy of itself.",
    formula: "ρ_k = Cov(X_t, X_t-k) / Var(X_t)",
    example: "Positive autocorrelation in returns indicates trending behavior.",
    related: ["Serial Correlation", "Time Series", "Mean Reversion"],
  },
  {
    id: 85,
    term: "Z-Score",
    category: "quant",
    description: "Number of standard deviations from the mean, used for standardization.",
    formula: "Z = (X - μ) / σ",
    example: "Price Z-score of -2 indicates oversold condition 2 standard deviations below mean.",
    related: ["Standard Deviation", "Normalization", "Statistical Arbitrage"],
  },
  {
    id: 86,
    term: "Market Regime",
    category: "analysis",
    description: "Prevailing market condition characterized by volatility, trend, and correlation patterns.",
    example: "Bull market regime with low volatility and positive trend.",
    related: ["Regime Switching", "Market Cycles", "Hidden Markov Models"],
  },
  {
    id: 87,
    term: "Backadjusted Data",
    category: "infrastructure",
    description: "Historical futures data adjusted for contract rolls to create continuous series.",
    example: "Adjust historical prices to account for futures contract expirations.",
    related: ["Futures Trading", "Continuous Contracts", "Data Quality"],
  },
  {
    id: 88,
    term: "Tick Data",
    category: "infrastructure",
    description: "Most granular market data showing every trade and quote change.",
    example: "Process millions of tick records to build accurate volume profiles.",
    related: ["Market Data", "High-Frequency Data", "Time and Sales"],
  },
  {
    id: 89,
    term: "Paper Trading",
    category: "execution",
    description: "Simulated trading with virtual money to test strategies without risk.",
    example: "Paper trade for 3 months before deploying real capital.",
    related: ["Simulation", "Forward Testing", "Risk-Free Practice"],
  },
  {
    id: 90,
    term: "Drawdown Duration",
    category: "risk",
    description: "Time period from a peak to recovery of that peak in portfolio value.",
    example: "Strategy took 6 months to recover from 15% drawdown.",
    related: ["Maximum Drawdown", "Recovery Period", "Underwater Curve"],
  },
  {
    id: 91,
    term: "Position Sizing",
    category: "risk",
    description: "Determining how much capital to allocate to each trade based on risk.",
    formula: "Position_Size = (Account_Risk × Capital) / Trade_Risk",
    example: "Risk 1% of $100k account with 50 pip stop = 20 lot position.",
    related: ["Kelly Criterion", "Fixed Fractional", "Risk Management"],
  },
  {
    id: 92,
    term: "Pyramiding",
    category: "strategies",
    description: "Adding to winning positions as they move in your favor.",
    example: "Add 25% more to position every time it moves 1 ATR in profit.",
    related: ["Position Management", "Scaling In", "Trend Following"],
  },
  {
    id: 93,
    term: "Market Breadth",
    category: "analysis",
    description: "Number of advancing vs declining securities, indicating market health.",
    example: "90% of stocks above 200-day MA indicates strong market breadth.",
    related: ["Advance/Decline Line", "Market Internals", "Breadth Indicators"],
  },
  {
    id: 94,
    term: "Sector Rotation",
    category: "strategies",
    description: "Moving investments between sectors based on economic cycle stages.",
    example: "Rotate from tech to utilities as economy enters recession.",
    related: ["Business Cycle", "Sector Analysis", "Asset Allocation"],
  },
  {
    id: 95,
    term: "Smart Order Router",
    acronym: "SOR",
    category: "execution",
    description: "System that automatically routes orders to best execution venue.",
    example: "SOR splits order across 3 exchanges to get best combined price.",
    related: ["Best Execution", "Order Routing", "Fragmented Markets"],
  },
  {
    id: 96,
    term: "Prime Broker",
    category: "infrastructure",
    description: "Financial institution providing services like lending, clearing, and custody to hedge funds.",
    example: "Use prime broker for leverage, stock borrowing, and trade clearing.",
    related: ["Hedge Funds", "Securities Lending", "Custody"],
  },
  {
    id: 97,
    term: "Rebate Rate",
    category: "execution",
    description: "Interest rate paid on cash collateral when borrowing stocks for short selling.",
    example: "Receive 0.25% rebate on cash posted for borrowed Tesla shares.",
    related: ["Short Selling", "Securities Lending", "Borrowing Costs"],
  },
  {
    id: 98,
    term: "Window Dressing",
    category: "analysis",
    description: "Practice of adjusting portfolio at period-end to improve appearance.",
    example: "Fund managers buy winning stocks before quarter-end reporting.",
    related: ["Quarter-End Effects", "Portfolio Management", "Reporting"],
  },
  {
    id: 99,
    term: "Spoofing",
    category: "execution",
    description: "Illegal practice of placing fake orders to manipulate prices.",
    example: "Place large fake sell orders to drive price down, then buy.",
    related: ["Market Manipulation", "Layering", "Regulatory Violations"],
  },
  {
    id: 100,
    term: "Co-location",
    category: "infrastructure",
    description: "Placing servers at exchange data centers for minimal latency.",
    example: "1 microsecond advantage from co-location worth millions in HFT.",
    related: ["Low Latency", "High-Frequency Trading", "Infrastructure"],
  },

  // Additional essential terms to reach comprehensive coverage
  {
    id: 101,
    term: "Spread Trading",
    category: "strategies",
    description: "Trading the price difference between related securities or contracts.",
    example: "Trade the spread between WTI and Brent crude oil.",
    related: ["Pairs Trading", "Calendar Spread", "Relative Value"],
  },
  {
    id: 102,
    term: "Pin Risk",
    category: "risk",
    description: "Risk that option will expire exactly at strike price, creating uncertainty.",
    example: "Stock at $100 at expiry with short $100 calls creates assignment uncertainty.",
    related: ["Options Expiration", "Assignment Risk", "Gamma Risk"],
  },
  {
    id: 103,
    term: "Theta Decay",
    category: "indicators",
    description: "Rate at which option value decreases as expiration approaches.",
    formula: "Theta = ∂V/∂t",
    example: "Option loses $0.05 per day as time decay accelerates near expiry.",
    related: ["Time Decay", "Options Greeks", "Theta"],
  },
  {
    id: 104,
    term: "Implied Volatility",
    acronym: "IV",
    category: "indicators",
    description: "Market's expectation of future volatility derived from option prices.",
    example: "IV of 30% means market expects 30% annual volatility.",
    related: ["Options Pricing", "Volatility Smile", "VIX"],
  },
  {
    id: 105,
    term: "Delta Hedging",
    category: "strategies",
    description: "Neutralizing directional risk by offsetting option delta with underlying.",
    example: "Short 100 calls with 0.5 delta, buy 50 shares to hedge.",
    related: ["Dynamic Hedging", "Market Making", "Greeks"],
  },
  {
    id: 106,
    term: "Contango",
    category: "analysis",
    description: "Futures market condition where future prices exceed spot prices.",
    example: "Oil futures at $55 while spot at $50 indicates contango.",
    related: ["Backwardation", "Futures Curve", "Roll Yield"],
  },
  {
    id: 107,
    term: "Backwardation",
    category: "analysis",
    description: "Futures market condition where future prices are below spot prices.",
    example: "Spot gold at $2000, futures at $1950 shows backwardation.",
    related: ["Contango", "Futures Curve", "Convenience Yield"],
  },
  {
    id: 108,
    term: "Roll Yield",
    category: "strategies",
    description: "Profit or loss from rolling futures contracts to maintain exposure.",
    example: "Earn positive roll yield in backwardated commodity markets.",
    related: ["Futures Trading", "Contango", "Carry Trade"],
  },
  {
    id: 109,
    term: "Correlation Breakdown",
    category: "risk",
    description: "When historically correlated assets diverge during stress periods.",
    example: "Stock-bond correlation turning positive during market crisis.",
    related: ["Correlation Risk", "Diversification Failure", "Tail Events"],
  },
  {
    id: 110,
    term: "Market Neutral",
    category: "strategies",
    description: "Strategy designed to profit regardless of market direction.",
    example: "Long value stocks, short growth stocks with zero net exposure.",
    related: ["Long/Short", "Beta Neutral", "Pairs Trading"],
  },
  {
    id: 111,
    term: "Factor Investing",
    category: "strategies",
    description: "Systematic approach targeting specific return drivers like value or momentum.",
    example: "Build portfolio of stocks with low P/E ratios for value factor.",
    related: ["Smart Beta", "Risk Factors", "Factor Models"],
  },
  {
    id: 112,
    term: "Systematic Trading",
    category: "strategies",
    description: "Rule-based trading approach with minimal human discretion.",
    example: "Computer executes all trades based on predefined algorithms.",
    related: ["Algorithmic Trading", "Quantitative Trading", "Rules-Based"],
  },
  {
    id: 113,
    term: "Discretionary Trading",
    category: "strategies",
    description: "Trading based on human judgment rather than systematic rules.",
    example: "Trader decides entries/exits based on experience and market feel.",
    related: ["Manual Trading", "Fundamental Analysis", "Intuition"],
  },
  {
    id: 114,
    term: "OHLC",
    acronym: "Open, High, Low, Close",
    category: "analysis",
    description: "Four key data points for each trading period used in technical analysis.",
    example: "Daily candle shows open $100, high $105, low $99, close $103.",
    related: ["Candlestick Charts", "Bar Charts", "Price Action"],
  },
  {
    id: 115,
    term: "Support and Resistance",
    category: "analysis",
    description: "Price levels where buying or selling pressure tends to emerge.",
    example: "$100 acts as resistance until broken, then becomes support.",
    related: ["Technical Analysis", "Price Levels", "Chart Patterns"],
  },
  {
    id: 116,
    term: "Breakout",
    category: "analysis",
    description: "Price movement through identified support or resistance level.",
    example: "Stock breaks above $50 resistance on high volume, signaling continuation.",
    related: ["Support/Resistance", "Volume Confirmation", "False Breakout"],
  },
  {
    id: 117,
    term: "Divergence",
    category: "analysis",
    description: "When price and indicator move in opposite directions, signaling reversal.",
    example: "Price makes new high but RSI makes lower high - bearish divergence.",
    related: ["Technical Indicators", "Reversal Signals", "Hidden Divergence"],
  },
  {
    id: 118,
    term: "Gap",
    category: "analysis",
    description: "Price difference between previous close and current open.",
    example: "Stock closes at $50, opens at $52 creating $2 gap up.",
    related: ["Gap Fill", "Overnight Risk", "Opening Range"],
  },
  {
    id: 119,
    term: "Moving Average",
    acronym: "MA",
    category: "indicators",
    description: "Average price over specified number of periods, smoothing price action.",
    formula: "SMA = Σ(Price) / N",
    example: "50-day MA at $100 acts as dynamic support in uptrend.",
    related: ["EMA", "SMA", "Trend Following"],
  },
  {
    id: 120,
    term: "EMA",
    acronym: "Exponential Moving Average",
    category: "indicators",
    description: "Moving average giving more weight to recent prices.",
    formula: "EMA = Price × K + EMA_yesterday × (1-K), where K = 2/(N+1)",
    example: "12-period EMA responds faster to price changes than SMA.",
    related: ["Moving Average", "MACD", "Technical Indicators"],
  },
  {
    id: 121,
    term: "Candlestick Patterns",
    category: "analysis",
    description: "Price patterns formed by one or more candlesticks indicating potential moves.",
    example: "Hammer at support suggests bullish reversal.",
    related: ["Doji", "Engulfing", "Price Action"],
  },
  {
    id: 122,
    term: "Chart Patterns",
    category: "analysis",
    description: "Recognizable price formations suggesting future movements.",
    example: "Head and shoulders pattern often precedes trend reversal.",
    related: ["Triangle", "Flag", "Double Top/Bottom"],
  },
  {
    id: 123,
    term: "Trend Line",
    category: "analysis",
    description: "Straight line connecting price points to identify trend direction.",
    example: "Connect series of higher lows to draw uptrend support line.",
    related: ["Support/Resistance", "Channel", "Technical Analysis"],
  },
  {
    id: 124,
    term: "Retracement",
    category: "analysis",
    description: "Temporary reversal within larger trend.",
    example: "50% retracement of rally from $100 to $200 targets $150.",
    related: ["Fibonacci", "Pullback", "Correction"],
  },
  {
    id: 125,
    term: "Range",
    category: "analysis",
    description: "Difference between high and low prices over a period.",
    formula: "Range = High - Low",
    example: "Daily range of $5 indicates volatility level.",
    related: ["ATR", "Volatility", "Trading Range"],
  },
  {
    id: 126,
    term: "Bid-Ask Spread",
    category: "execution",
    description: "Difference between best buy and sell prices in order book.",
    formula: "Spread = Ask - Bid",
    example: "Bid $99.95, Ask $100.05 creates $0.10 spread.",
    related: ["Liquidity", "Market Making", "Transaction Costs"],
  },
  {
    id: 127,
    term: "Limit Order",
    category: "execution",
    description: "Order to buy or sell at specific price or better.",
    example: "Limit buy at $100 only executes at $100 or lower.",
    related: ["Order Types", "Market Order", "Passive Order"],
  },
  {
    id: 128,
    term: "Market Order",
    category: "execution",
    description: "Order to buy or sell immediately at best available price.",
    example: "Market buy executes instantly but price not guaranteed.",
    related: ["Order Types", "Limit Order", "Slippage"],
  },
  {
    id: 129,
    term: "Stop Loss",
    category: "execution",
    description: "Order to close position when price reaches specified loss level.",
    example: "Long at $100 with stop at $95 limits loss to 5%.",
    related: ["Risk Management", "Stop Order", "Trailing Stop"],
  },
  {
    id: 130,
    term: "Take Profit",
    category: "execution",
    description: "Order to close position when price reaches target profit level.",
    example: "Long at $100 with take profit at $110 locks in 10% gain.",
    related: ["Profit Target", "Limit Order", "Exit Strategy"],
  },
  {
    id: 131,
    term: "Trailing Stop",
    category: "execution",
    description: "Stop loss that moves with favorable price movement to lock profits.",
    example: "Trailing stop 5% below high follows price up but not down.",
    related: ["Stop Loss", "Dynamic Stop", "Profit Protection"],
  },
  {
    id: 132,
    term: "OCO Order",
    acronym: "One Cancels Other",
    category: "execution",
    description: "Paired orders where execution of one cancels the other.",
    example: "Stop loss at $95 and take profit at $105 - one fills, other cancels.",
    related: ["Bracket Order", "Order Types", "Risk Management"],
  },
  {
    id: 133,
    term: "Bracket Order",
    category: "execution",
    description: "Entry order with attached stop loss and take profit orders.",
    example: "Buy at market with automatic stop at -2% and target at +5%.",
    related: ["OCO Order", "Risk Management", "Order Types"],
  },
  {
    id: 134,
    term: "Partial Fill",
    category: "execution",
    description: "When only portion of order is executed at desired price.",
    example: "Order for 1000 shares but only 600 filled at limit price.",
    related: ["Liquidity", "Order Execution", "All or None"],
  },
  {
    id: 135,
    term: "Margin",
    category: "risk",
    description: "Borrowed funds to increase position size and potential returns.",
    example: "Use 4:1 margin to control $100k position with $25k capital.",
    related: ["Leverage", "Margin Call", "Buying Power"],
  },
  {
    id: 136,
    term: "Margin Call",
    category: "risk",
    description: "Broker demand for additional funds when account equity falls below requirement.",
    example: "Position loss triggers call to deposit funds or face liquidation.",
    related: ["Margin", "Maintenance Margin", "Forced Liquidation"],
  },
  {
    id: 137,
    term: "Leverage",
    category: "risk",
    description: "Using borrowed capital to increase potential returns (and risks).",
    formula: "Leverage = Total_Position_Value / Account_Equity",
    example: "10:1 leverage means $10k controls $100k position.",
    related: ["Margin", "Risk Management", "Position Sizing"],
  },
  {
    id: 138,
    term: "Short Selling",
    category: "strategies",
    description: "Selling borrowed assets hoping to buy back at lower price.",
    example: "Borrow and sell stock at $100, buy back at $90 for $10 profit.",
    related: ["Short Interest", "Short Squeeze", "Borrowing Costs"],
  },
  {
    id: 139,
    term: "Short Squeeze",
    category: "analysis",
    description: "Rapid price increase forcing short sellers to cover positions.",
    example: "GameStop surge as shorts rushed to buy back borrowed shares.",
    related: ["Short Interest", "Gamma Squeeze", "Short Covering"],
  },
  {
    id: 140,
    term: "Funding Rate",
    category: "execution",
    description: "Periodic payment between long and short positions in perpetual futures.",
    example: "Positive funding means longs pay shorts 0.01% every 8 hours.",
    related: ["Perpetual Futures", "Carry Cost", "Derivatives"],
  },
  {
    id: 141,
    term: "Arbitrage-Free Pricing",
    category: "quant",
    description: "Pricing model ensuring no risk-free profit opportunities exist.",
    example: "Options priced to eliminate guaranteed profits from conversions.",
    related: ["No-Arbitrage", "Efficient Markets", "Fair Value"],
  },
  {
    id: 142,
    term: "Stationarity",
    category: "quant",
    description: "Statistical property where mean and variance remain constant over time.",
    example: "Price differences between pairs often stationary while individual prices are not.",
    related: ["Time Series", "ADF Test", "Cointegration"],
  },
  {
    id: 143,
    term: "Heteroskedasticity",
    category: "quant",
    description: "Non-constant variance in time series, common in financial data.",
    example: "Volatility clustering where large moves follow large moves.",
    related: ["GARCH", "Volatility Modeling", "Time Series"],
  },
  {
    id: 144,
    term: "Survivorship Bias",
    category: "quant",
    description: "Distortion from only analyzing assets that still exist.",
    example: "Backtest on S&P 500 current members ignores delisted companies.",
    related: ["Backtesting Bias", "Look-Ahead Bias", "Data Quality"],
  },
  {
    id: 145,
    term: "Look-Ahead Bias",
    category: "quant",
    description: "Using information not available at the time of trade in backtests.",
    example: "Using earnings data before official release date in historical test.",
    related: ["Backtesting Bias", "Data Snooping", "Point-in-Time Data"],
  },
  {
    id: 146,
    term: "Overfitting",
    category: "quant",
    description: "Creating model too complex that fits noise rather than signal.",
    example: "Strategy with 50 parameters works perfectly in backtest but fails live.",
    related: ["Curve Fitting", "Out-of-Sample", "Model Validation"],
  },
  {
    id: 147,
    term: "Walk-Forward Optimization",
    category: "quant",
    description: "Rolling window optimization to test strategy robustness.",
    example: "Optimize on 2 years, test on 6 months, slide forward, repeat.",
    related: ["Backtesting", "Robustness", "Parameter Optimization"],
  },
  {
    id: 148,
    term: "Feature Selection",
    category: "quant",
    description: "Choosing relevant variables for predictive models.",
    example: "Select top 10 technical indicators from 100 based on predictive power.",
    related: ["Machine Learning", "Dimensionality Reduction", "Model Building"],
  },
  {
    id: 149,
    term: "Cross-Validation",
    category: "quant",
    description: "Technique to assess model performance on unseen data.",
    example: "K-fold validation divides data into K parts for training/testing.",
    related: ["Model Validation", "Overfitting", "Machine Learning"],
  },
  {
    id: 150,
    term: "Ensemble Methods",
    category: "quant",
    description: "Combining multiple models to improve predictions.",
    example: "Average predictions from random forest, neural net, and SVM.",
    related: ["Machine Learning", "Model Averaging", "Bagging/Boosting"],
  },
]

export const workshopTechniques = {
  foundation: [
    {
      name: "Event-Driven Architecture",
      desc: "Build systems that react to market events in real-time using message queues.",
      tags: ["Kafka", "RabbitMQ", "Redis"],
    },
    {
      name: "Microservices Design",
      desc: "Separate concerns into independent services for scalability.",
      tags: ["Docker", "Kubernetes", "gRPC"],
    },
    {
      name: "Database Architecture",
      desc: "Use time-series databases for market data, relational for trades.",
      tags: ["InfluxDB", "PostgreSQL", "MongoDB"],
    },
  ],
  dataAnalysis: [
    {
      name: "Data Pipeline Design",
      desc: "Build robust pipelines for real-time and historical data processing.",
      tags: ["Apache Airflow", "ETL", "Streaming"],
    },
    {
      name: "Feature Engineering",
      desc: "Create powerful features from raw market data.",
      tags: ["Pandas", "NumPy", "TA-Lib"],
    },
    {
      name: "Statistical Analysis",
      desc: "Apply rigorous statistical tests to validate strategies.",
      tags: ["Hypothesis Testing", "P-Values", "Confidence Intervals"],
    },
  ],
  strategies: [
    {
      name: "Strategy Development Framework",
      desc: "Systematic approach from idea generation to production deployment.",
      tags: ["Backtesting", "Optimization", "Validation"],
    },
    {
      name: "Multi-Strategy Portfolio",
      desc: "Combine uncorrelated strategies for smoother returns.",
      tags: ["Diversification", "Correlation", "Risk Budgeting"],
    },
    {
      name: "Adaptive Strategies",
      desc: "Build strategies that adapt to changing market conditions.",
      tags: ["Regime Detection", "Parameter Adjustment", "ML"],
    },
  ],
  execution: [
    {
      name: "Smart Order Routing",
      desc: "Optimize order execution across multiple venues.",
      tags: ["Best Execution", "Latency", "Liquidity"],
    },
    {
      name: "Execution Algorithms",
      desc: "Implement TWAP, VWAP, and custom execution algos.",
      tags: ["Slicing", "Dark Pools", "Impact Minimization"],
    },
    {
      name: "Order Management System",
      desc: "Build robust OMS for order lifecycle management.",
      tags: ["State Machine", "Error Handling", "Audit Trail"],
    },
  ],
  risk: [
    {
      name: "Portfolio Risk Framework",
      desc: "Comprehensive risk management at position and portfolio level.",
      tags: ["VaR", "Stress Testing", "Limits"],
    },
    {
      name: "Dynamic Position Sizing",
      desc: "Adjust position sizes based on market conditions and performance.",
      tags: ["Kelly Criterion", "Volatility Scaling", "Risk Parity"],
    },
    {
      name: "Risk Monitoring Dashboard",
      desc: "Real-time monitoring of all risk metrics and exposures.",
      tags: ["Grafana", "Alerts", "Visualization"],
    },
  ],
  monitoring: [
    {
      name: "System Health Monitoring",
      desc: "Track system performance, latency, and errors.",
      tags: ["Prometheus", "Logging", "Metrics"],
    },
    {
      name: "Strategy Performance Tracking",
      desc: "Monitor strategy behavior vs expectations.",
      tags: ["P&L Attribution", "Slippage Analysis", "Benchmarking"],
    },
    {
      name: "Alerting Framework",
      desc: "Intelligent alerts for system issues and opportunities.",
      tags: ["PagerDuty", "Webhooks", "Escalation"],
    },
  ],
}

export const bestPractices = [
  {
    title: "Always Start with Paper Trading",
    content:
      "Never deploy a strategy with real money until it has been thoroughly tested in paper trading for at least 3-6 months.",
    tips: [
      "Track all metrics: win rate, profit factor, max drawdown",
      "Compare paper results to backtest results",
      "Test during different market conditions",
    ],
  },
  {
    title: "Implement Robust Risk Management",
    content:
      "Risk management should be built into every level of your system, from position sizing to portfolio allocation.",
    tips: [
      "Use Kelly Criterion or fractional Kelly for position sizing",
      "Implement stop losses and maximum drawdown limits",
      "Diversify across uncorrelated strategies",
    ],
  },
  {
    title: "Version Control Everything",
    content:
      "Use Git for code, but also version control your configurations, model parameters, and even trading rules.",
    tips: [
      "Tag releases with performance metrics",
      "Document all parameter changes",
      "Maintain separate branches for development and production",
    ],
  },
  {
    title: "Monitor System Health Continuously",
    content:
      "Set up comprehensive monitoring and alerting for both technical issues and strategy performance degradation.",
    tips: [
      "Monitor latency, error rates, and system resources",
      "Track strategy performance vs. expectations",
      "Set up alerts for unusual market conditions",
    ],
  },
  {
    title: "Avoid Overfitting at All Costs",
    content:
      "The biggest danger in quantitative trading is creating strategies that work perfectly on historical data but fail in live trading.",
    tips: [
      "Use walk-forward analysis for validation",
      "Keep models simple - fewer parameters are better",
      "Test on out-of-sample data from different time periods",
    ],
  },
  {
    title: "Build for Scale from Day One",
    content:
      "Design your system architecture to handle increased data volumes, more strategies, and larger capital without major rewrites.",
    tips: [
      "Use asynchronous processing for non-critical tasks",
      "Implement horizontal scaling capabilities",
      "Design with multi-asset and multi-strategy in mind",
    ],
  },
]
