export type Ingredient = {
  id: string
  title: string
  desc: string
  category: string
  complexity: 1 | 2 | 3
  tags: string[]
  icon: "BarChart" | "BrainCircuit" | "Bot" | "ShieldCheck" | "Rocket" | "Beaker"
}

export type Strategy = {
  id: string
  title: string
  desc: string
  type: string
  category: string
  difficulty: 1 | 2 | 3 | 4 | 5
  components: string[]
  metrics: { label: string; value: string }[]
  implementation: { title: string; desc: string }[]
  risks: string
  featured?: boolean
}

export const ingredients: Ingredient[] = [
  {
    id: "ohlcv",
    title: "OHLCV Data",
    desc: "The foundation of technical analysis. Open, High, Low, Close, and Volume data forms the basis for most trading strategies and indicators.",
    category: "Data",
    complexity: 1,
    tags: ["Price Action", "Historical Data", "Candlesticks"],
    icon: "BarChart",
  },
  {
    id: "orderbook",
    title: "Order Book Data",
    desc: "Real-time Level 2/3 market depth showing all buy and sell orders. Essential for market making and understanding true supply/demand dynamics.",
    category: "Data",
    complexity: 2,
    tags: ["Market Depth", "Liquidity", "Microstructure"],
    icon: "BarChart",
  },
  {
    id: "tickdata",
    title: "Tick Data",
    desc: "Every individual trade and quote update. The most granular data available, used by HFT firms for microsecond-level analysis.",
    category: "Data",
    complexity: 3,
    tags: ["High Frequency", "Time & Sales", "Raw Feed"],
    icon: "BarChart",
  },
  {
    id: "alternative",
    title: "Alternative Data",
    desc: "Non-traditional data sources like satellite imagery, web scraping, credit card transactions, and social media sentiment for unique alpha generation.",
    category: "Data",
    complexity: 3,
    tags: ["Satellite", "Web Data", "Sentiment"],
    icon: "BarChart",
  },
  {
    id: "options-chain",
    title: "Options Chain Data",
    desc: "Complete options chain with Greeks, implied volatility, and open interest. Critical for volatility trading and hedging strategies.",
    category: "Data",
    complexity: 2,
    tags: ["Greeks", "IV Surface", "Skew"],
    icon: "BarChart",
  },
  {
    id: "fundamental",
    title: "Fundamental Data",
    desc: "Financial statements, earnings reports, economic indicators, and company metrics for value-based strategies and macro trading.",
    category: "Data",
    complexity: 1,
    tags: ["Financials", "Ratios", "Earnings"],
    icon: "BarChart",
  },
  {
    id: "technical",
    title: "Technical Indicators",
    desc: "Mathematical calculations on price and volume data. From simple moving averages to complex oscillators like RSI, MACD, and Bollinger Bands.",
    category: "Analysis",
    complexity: 1,
    tags: ["Moving Averages", "Oscillators", "Momentum"],
    icon: "Beaker",
  },
  {
    id: "statistical",
    title: "Statistical Models",
    desc: "Advanced mathematical models including ARIMA, GARCH for volatility, cointegration tests, and regime-switching models for market analysis.",
    category: "Analysis",
    complexity: 3,
    tags: ["Time Series", "Cointegration", "GARCH"],
    icon: "Beaker",
  },
  {
    id: "microstructure",
    title: "Market Microstructure",
    desc: "Study of order flow, market impact, bid-ask spreads, and price discovery mechanisms. Critical for execution optimization.",
    category: "Analysis",
    complexity: 3,
    tags: ["Order Flow", "Market Impact", "Spreads"],
    icon: "Beaker",
  },
  {
    id: "factor",
    title: "Factor Models",
    desc: "Decompose returns into systematic factors like value, momentum, quality, and volatility. Foundation of smart beta and risk premia strategies.",
    category: "Analysis",
    complexity: 2,
    tags: ["Fama-French", "Risk Factors", "Alpha"],
    icon: "Beaker",
  },
  {
    id: "wavelet",
    title: "Wavelet Analysis",
    desc: "Multi-resolution time-frequency analysis for detecting patterns at different time scales. Superior to Fourier for non-stationary financial data.",
    category: "Analysis",
    complexity: 3,
    tags: ["Signal Processing", "Multi-Scale", "Denoising"],
    icon: "Beaker",
  },
  {
    id: "entropy",
    title: "Market Entropy",
    desc: "Information theory applied to markets. Measure market efficiency, predictability, and regime changes using Shannon entropy and mutual information.",
    category: "Analysis",
    complexity: 3,
    tags: ["Information Theory", "Efficiency", "Complexity"],
    icon: "Beaker",
  },
  {
    id: "supervised",
    title: "Supervised Learning",
    desc: "Classification and regression models for price prediction. Includes Random Forests, XGBoost, and Support Vector Machines trained on labeled data.",
    category: "ML/AI",
    complexity: 2,
    tags: ["Random Forest", "XGBoost", "SVM"],
    icon: "BrainCircuit",
  },
  {
    id: "deeplearning",
    title: "Deep Learning",
    desc: "Neural networks including LSTMs for time series, CNNs for pattern recognition, and Transformers for market regime detection.",
    category: "ML/AI",
    complexity: 3,
    tags: ["LSTM", "Transformers", "Autoencoders"],
    icon: "BrainCircuit",
  },
  {
    id: "reinforcement",
    title: "Reinforcement Learning",
    desc: "Agents that learn optimal trading policies through interaction with markets. Uses Q-learning, DQN, and Policy Gradient methods.",
    category: "ML/AI",
    complexity: 3,
    tags: ["Q-Learning", "PPO", "Adaptive"],
    icon: "BrainCircuit",
  },
  {
    id: "nlp",
    title: "NLP & Sentiment",
    desc: "Natural language processing for news, social media, and earnings calls. Extracts market sentiment and trading signals from text data.",
    category: "ML/AI",
    complexity: 2,
    tags: ["BERT", "Sentiment", "News Analysis"],
    icon: "BrainCircuit",
  },
  {
    id: "gnn",
    title: "Graph Neural Networks",
    desc: "Model complex relationships between assets using graph structures. Captures market connectivity, sector relationships, and contagion effects.",
    category: "ML/AI",
    complexity: 3,
    tags: ["Network Analysis", "Contagion", "GCN"],
    icon: "BrainCircuit",
  },
  {
    id: "gan",
    title: "GANs for Finance",
    desc: "Generative Adversarial Networks for synthetic data generation, scenario simulation, and improving backtest robustness.",
    category: "ML/AI",
    complexity: 3,
    tags: ["Synthetic Data", "Simulation", "WGAN"],
    icon: "BrainCircuit",
  },
  {
    id: "position",
    title: "Position Sizing",
    desc: "Optimal capital allocation using Kelly Criterion, fixed fractional, or volatility-based methods to maximize returns while controlling risk.",
    category: "Risk",
    complexity: 2,
    tags: ["Kelly Criterion", "Risk Parity", "Volatility Sizing"],
    icon: "ShieldCheck",
  },
  {
    id: "portfolio",
    title: "Portfolio Optimization",
    desc: "Modern portfolio theory, mean-variance optimization, Black-Litterman models, and risk budgeting for multi-asset allocation.",
    category: "Risk",
    complexity: 3,
    tags: ["Markowitz", "Black-Litterman", "Efficient Frontier"],
    icon: "ShieldCheck",
  },
  {
    id: "metrics",
    title: "Risk Metrics",
    desc: "VaR, CVaR, Sharpe ratio, maximum drawdown, and other metrics to measure and monitor portfolio risk in real-time.",
    category: "Risk",
    complexity: 1,
    tags: ["Value at Risk", "Sharpe Ratio", "Drawdown"],
    icon: "ShieldCheck",
  },
  {
    id: "hedging",
    title: "Hedging Strategies",
    desc: "Dynamic hedging, options overlays, tail risk protection, and correlation hedges to protect portfolios during market stress.",
    category: "Risk",
    complexity: 3,
    tags: ["Options Hedging", "Tail Risk", "Delta Neutral"],
    icon: "ShieldCheck",
  },
  {
    id: "stress",
    title: "Stress Testing",
    desc: "Scenario analysis, historical stress tests, and Monte Carlo simulations to evaluate portfolio performance under extreme market conditions.",
    category: "Risk",
    complexity: 2,
    tags: ["Scenarios", "Black Swan", "Tail Events"],
    icon: "ShieldCheck",
  },
  {
    id: "liquidity",
    title: "Liquidity Risk",
    desc: "Model market impact, slippage, and liquidation costs. Critical for large positions and during market stress when liquidity evaporates.",
    category: "Risk",
    complexity: 3,
    tags: ["Market Impact", "Slippage", "Liquidation"],
    icon: "ShieldCheck",
  },
  {
    id: "algos",
    title: "Execution Algorithms",
    desc: "TWAP, VWAP, Implementation Shortfall, and other algorithms to minimize market impact and achieve best execution.",
    category: "Execution",
    complexity: 2,
    tags: ["TWAP", "VWAP", "Iceberg"],
    icon: "Rocket",
  },
  {
    id: "routing",
    title: "Smart Order Routing",
    desc: "Intelligent routing across multiple venues, dark pools, and exchanges to find best prices and hidden liquidity.",
    category: "Execution",
    complexity: 3,
    tags: ["Multi-Venue", "Dark Pools", "Best Execution"],
    icon: "Rocket",
  },
  {
    id: "latency",
    title: "Latency Optimization",
    desc: "Co-location, network optimization, FPGA acceleration, and kernel bypass for microsecond-level execution speed.",
    category: "Execution",
    complexity: 3,
    tags: ["Co-location", "FPGA", "Low Latency"],
    icon: "Rocket",
  },
  {
    id: "infrastructure",
    title: "Trading Infrastructure",
    desc: "FIX connectivity, API integration, message queues, and databases optimized for high-throughput trading systems.",
    category: "Execution",
    complexity: 2,
    tags: ["FIX Protocol", "REST/WebSocket", "Message Queues"],
    icon: "Rocket",
  },
  {
    id: "tca",
    title: "Transaction Cost Analysis",
    desc: "Pre-trade and post-trade analysis to measure execution quality, slippage, and optimize future trades.",
    category: "Execution",
    complexity: 2,
    tags: ["Slippage Analysis", "Cost Attribution", "Benchmarking"],
    icon: "Rocket",
  },
  {
    id: "matching",
    title: "Matching Engine",
    desc: "Understanding exchange matching algorithms: FIFO, Pro-Rata, and hybrid models. Critical for HFT queue position strategies.",
    category: "Execution",
    complexity: 3,
    tags: ["FIFO", "Pro-Rata", "Queue Priority"],
    icon: "Rocket",
  },
  {
    id: "kalman",
    title: "Kalman Filters",
    desc: "Dynamic state estimation for hedge ratios, signal extraction from noisy data, and adaptive parameter updating in real-time.",
    category: "Advanced",
    complexity: 3,
    tags: ["State Estimation", "Noise Filtering", "Adaptive"],
    icon: "Bot",
  },
  {
    id: "hmm",
    title: "Hidden Markov Models",
    desc: "Regime detection and switching models to identify market states and adapt strategies to changing conditions automatically.",
    category: "Advanced",
    complexity: 3,
    tags: ["Regime Detection", "State Switching", "Baum-Welch"],
    icon: "Bot",
  },
  {
    id: "copula",
    title: "Copula Models",
    desc: "Model complex non-linear dependencies between assets, especially useful for tail risk and extreme event correlation.",
    category: "Advanced",
    complexity: 3,
    tags: ["Tail Dependence", "Non-Linear", "Risk Modeling"],
    icon: "Bot",
  },
  {
    id: "mle",
    title: "Maximum Likelihood",
    desc: "Parameter estimation for complex models using MLE. Essential for calibrating stochastic volatility models and regime-switching systems.",
    category: "Advanced",
    complexity: 3,
    tags: ["Optimization", "Calibration", "Statistical Inference"],
    icon: "Bot",
  },
  {
    id: "spectral",
    title: "Spectral Analysis",
    desc: "Frequency domain analysis to identify cycles, seasonality, and periodic patterns in financial time series data.",
    category: "Advanced",
    complexity: 3,
    tags: ["FFT", "Periodogram", "Cycles"],
    icon: "Bot",
  },
  {
    id: "hawkes",
    title: "Hawkes Processes",
    desc: "Self-exciting point processes for modeling clustered events like trades, order arrivals, and volatility bursts in high-frequency data.",
    category: "Advanced",
    complexity: 3,
    tags: ["Point Process", "Self-Exciting", "HFT"],
    icon: "Bot",
  },
]

export const strategies: Strategy[] = [
  {
    id: "adaptive-momentum",
    title: "Adaptive Momentum Breakout",
    desc: "Multi-timeframe momentum strategy with dynamic parameter adjustment based on market regime. Combines price breakouts, volume surge detection, and volatility filters to capture strong directional moves while avoiding false signals in choppy markets.",
    type: "Trend Following",
    category: "momentum",
    difficulty: 3,
    components: ["OHLCV Data", "Volume Profile", "ATR", "Regime Detection", "Position Sizing"],
    metrics: [
      { label: "Win Rate", value: "68%" },
      { label: "Sharpe", value: "2.3" },
      { label: "Annual Return", value: "45%" },
      { label: "Max Drawdown", value: "-12%" },
    ],
    implementation: [
      {
        title: "Multi-Timeframe Setup",
        desc: "Collect OHLCV data across 5m, 15m, 1h, 4h, and daily timeframes for trend alignment",
      },
      {
        title: "Regime Identification",
        desc: "Use Hidden Markov Model to classify market as trending, ranging, or volatile",
      },
      {
        title: "Dynamic Signal Generation",
        desc: "Adjust breakout thresholds based on regime: tight in trends, wide in ranges",
      },
      { title: "Risk Management", desc: "Volatility-based position sizing with 2% portfolio risk per trade" },
    ],
    risks: "Vulnerable to whipsaws in ranging markets. Requires robust regime detection to avoid overtrading.",
    featured: true,
  },
  {
    id: "stat-arb",
    title: "Multi-Factor Statistical Arbitrage",
    desc: "Advanced pairs trading system using cointegration, machine learning for pair selection, and Kalman filters for dynamic hedge ratio adjustment. Incorporates multiple factors including momentum, value, and microstructure signals for enhanced alpha generation.",
    type: "Market Neutral",
    category: "arbitrage market-neutral",
    difficulty: 4,
    components: ["Tick Data", "Cointegration Tests", "Kalman Filter", "Factor Models", "ML Classification"],
    metrics: [
      { label: "Win Rate", value: "82%" },
      { label: "Sharpe", value: "3.1" },
      { label: "Annual Return", value: "28%" },
      { label: "Max Drawdown", value: "-8%" },
    ],
    implementation: [
      { title: "Universe Selection", desc: "Filter liquid stocks with >$10M daily volume, stable fundamentals" },
      { title: "Pair Formation", desc: "Apply Johansen test and ML clustering to identify stable pairs" },
      { title: "Dynamic Hedging", desc: "Update hedge ratios every hour using Kalman filter" },
      { title: "Multi-Factor Enhancement", desc: "Overlay momentum and microstructure signals for timing" },
    ],
    risks: "Correlation breakdown during market stress. Requires sophisticated execution to minimize costs.",
  },
  {
    id: "transformer-alpha",
    title: "Transformer-Based Alpha Generation",
    desc: "State-of-the-art deep learning system using Transformer architecture for multi-modal data fusion. Combines price patterns, news sentiment, options flow, and alternative data with attention mechanisms for superior prediction accuracy.",
    type: "Machine Learning",
    category: "ml",
    difficulty: 5,
    components: ["Alternative Data", "Transformers", "NLP Sentiment", "Feature Engineering", "Ensemble Methods"],
    metrics: [
      { label: "Win Rate", value: "71%" },
      { label: "Sharpe", value: "2.8" },
      { label: "Annual Return", value: "52%" },
      { label: "Max Drawdown", value: "-15%" },
    ],
    implementation: [
      { title: "Multi-Modal Data Pipeline", desc: "Aggregate price, news, satellite, social media, and options data" },
      { title: "Feature Engineering", desc: "Create 1000+ features including technical, fundamental, and alternative" },
      { title: "Transformer Architecture", desc: "Train multi-head attention model on 5 years of data" },
      { title: "Online Learning", desc: "Continuously retrain with sliding window approach" },
    ],
    risks: "Model degradation, overfitting, and high computational costs. Requires constant monitoring.",
    featured: true,
  },
  {
    id: "fpga-mm",
    title: "FPGA-Accelerated Market Making",
    desc: "Sub-microsecond market making system with FPGA hardware acceleration. Features advanced queue position modeling, adverse selection detection, and dynamic inventory management across multiple venues simultaneously.",
    type: "High Frequency",
    category: "hft",
    difficulty: 5,
    components: ["Order Book Data", "Microstructure", "FPGA/Co-location", "Queue Models", "Inventory Control"],
    metrics: [
      { label: "Win Rate", value: "89%" },
      { label: "Sharpe", value: "4.2" },
      { label: "Trades/Day", value: "25k" },
      { label: "Max Drawdown", value: "-5%" },
    ],
    implementation: [
      { title: "Infrastructure Setup", desc: "Deploy FPGA cards in co-located servers, sub-500ns latency" },
      { title: "Microstructure Analytics", desc: "Model order flow toxicity, queue position probability" },
      { title: "Dynamic Quoting", desc: "Adjust spreads based on inventory, volatility, and toxicity" },
      { title: "Risk Controls", desc: "Hardware kill switches, position limits, loss breakers" },
    ],
    risks: "Technology arms race, regulatory changes, and adverse selection from informed traders.",
  },
  {
    id: "defi-mev",
    title: "Cross-Chain MEV Arbitrage",
    desc: "Sophisticated multi-chain arbitrage system exploiting price inefficiencies across DEXs, bridges, and lending protocols. Includes MEV protection, gas optimization, and flash loan strategies across Ethereum, BSC, Arbitrum, and Polygon.",
    type: "Cryptocurrency",
    category: "crypto arbitrage",
    difficulty: 4,
    components: ["Blockchain Data", "DEX Aggregators", "Flash Loans", "MEV Protection", "Gas Optimization"],
    metrics: [
      { label: "Win Rate", value: "92%" },
      { label: "Sharpe", value: "3.7" },
      { label: "APY", value: "287%" },
      { label: "Max Drawdown", value: "-10%" },
    ],
    implementation: [
      { title: "Multi-Chain Infrastructure", desc: "Deploy contracts on ETH, BSC, Arbitrum, Polygon with bridges" },
      { title: "Price Monitoring", desc: "Real-time mempool monitoring and DEX price feeds" },
      { title: "Execution Logic", desc: "Calculate profit after gas, slippage, and bridge fees" },
      { title: "MEV Protection", desc: "Use Flashbots, private mempools, and commit-reveal schemes" },
    ],
    risks: "Smart contract vulnerabilities, bridge hacks, and regulatory uncertainty.",
  },
  {
    id: "vol-premium",
    title: "Dynamic Volatility Premium Harvesting",
    desc: "Systematic short volatility strategy with machine learning-based regime detection. Dynamically adjusts option structures and hedge ratios based on volatility forecasts, term structure, and skew analysis.",
    type: "Derivatives",
    category: "options market-neutral",
    difficulty: 4,
    components: ["Options Chain", "IV Surface", "GARCH Models", "Greeks Management", "Tail Hedging"],
    metrics: [
      { label: "Win Rate", value: "74%" },
      { label: "Sharpe", value: "2.5" },
      { label: "Annual Return", value: "35%" },
      { label: "Max Drawdown", value: "-18%" },
    ],
    implementation: [
      { title: "Volatility Analysis", desc: "Compare implied vs realized vol using GARCH and ML models" },
      { title: "Structure Selection", desc: "Choose between strangles, condors, or butterflies based on skew" },
      { title: "Dynamic Delta Hedging", desc: "Rebalance delta hourly, gamma scalp intraday moves" },
      { title: "Tail Risk Management", desc: "Maintain 5-10% in far OTM puts, scale with VIX level" },
    ],
    risks: "Volatility spikes can cause severe losses. Requires sophisticated risk management.",
  },
]
