name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Type check
        run: npm run typecheck

      - name: Run tests (jsdom)
        run: npx vitest run --environment=jsdom --reporter=verbose
        continue-on-error: true

      - name: Build static site
        run: npm run build

      - name: Upload static export artifact
        uses: actions/upload-artifact@v4
        with:
          name: nexus-cipher-static-out
          path: out


